# Generated by Django 6.0.2 on 2026-02-14 23:28

import compliance.registry
import django.db.models.deletion
import onboarding.registry
from django.conf import settings
from django.db import migrations, models

import django_stratagem.fields
import django_stratagem.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('us', 'United States'), ('uk', 'United Kingdom'), ('au', 'Australia')], max_length=50)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('compliance_strategy', django_stratagem.fields.RegistryClassField(blank=True, default='', registry=compliance.registry.ComplianceRegistry, validators=[django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(compliance.registry.ComplianceRegistry), django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(compliance.registry.ComplianceRegistry)])),
                ('compliance_handler', django_stratagem.fields.RegistryField(blank=True, default='', registry=compliance.registry.ComplianceRegistry, validators=[django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(compliance.registry.ComplianceRegistry), django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(compliance.registry.ComplianceRegistry)])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Firm Administrator'), ('manager', 'Project Manager'), ('coordinator', 'Safety Coordinator')], max_length=30)),
                ('onboarding_preference', django_stratagem.fields.RegistryClassField(blank=True, default='', registry=onboarding.registry.OnboardingRegistry, validators=[django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(onboarding.registry.OnboardingRegistry), django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(onboarding.registry.OnboardingRegistry)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='platform_core.firm')),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trade', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='platform_core.firm')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractorEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('foreman', 'Foreman'), ('worker', 'Field Worker'), ('safety_officer', 'Safety Officer')], max_length=30)),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='platform_core.subcontractor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
