# Generated by Django 6.0.2 on 2026-02-16 06:45

from django.db import migrations, models

import django_stratagem.fields
import django_stratagem.validators
import tests.exporters.registry


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exporter_type",
                    django_stratagem.fields.RegistryClassField(
                        max_length=100,
                        registry=tests.exporters.registry.ExporterRegistry,
                        validators=[
                            django_stratagem.validators.ClassnameValidator(None),
                            django_stratagem.validators.RegistryValidator(tests.exporters.registry.ExporterRegistry),
                            django_stratagem.validators.ClassnameValidator(None),
                            django_stratagem.validators.RegistryValidator(tests.exporters.registry.ExporterRegistry),
                        ],
                    ),
                ),
            ],
        ),
    ]
