# Generated by Django 6.0.2 on 2026-02-17 19:26

import django_stratagem.fields
import tests.exporters.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter_type', django_stratagem.fields.RegistryClassField(max_length=100, registry=tests.exporters.registry.ExporterRegistry)),
            ],
        ),
    ]
