# Generated by Django 6.0.2 on 2026-02-14 23:28

import django.db.models.deletion
from django.db import migrations, models

import billing.registry
import django_stratagem.fields
import django_stratagem.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_model', django_stratagem.fields.RegistryClassField(blank=True, default='', registry=billing.registry.BillingModelRegistry, validators=[django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(billing.registry.BillingModelRegistry), django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(billing.registry.BillingModelRegistry)])),
                ('invoicing_strategy', django_stratagem.fields.HierarchicalRegistryField(blank=True, default='', registry=billing.registry.InvoicingStrategyRegistry, validators=[django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(billing.registry.InvoicingStrategyRegistry), django_stratagem.validators.ClassnameValidator(None), django_stratagem.validators.RegistryValidator(billing.registry.InvoicingStrategyRegistry)])),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='platform_core.firm')),
            ],
        ),
    ]
