"""`startregistry` management command: scaffold a new registry into an app."""

from __future__ import annotations

import re
from pathlib import Path

from django.core.management.base import CommandError


def to_snake(name: str) -> str:
    """Convert a CamelCase or PascalCase name to snake_case."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def render_registry_module(name: str, module: str) -> str:
    """Return the source for a registry module defining a Registry + Interface."""
    registry_cls = f"{name}Registry"
    interface_cls = f"{name}Interface"
    return f'''"""Registry definition generated by `manage.py startregistry`."""

from django_stratagem.interfaces import Interface
from django_stratagem.registry import Registry


class {registry_cls}(Registry):
    """Registry of {name} implementations."""

    implementations_module = "{module}"


class {interface_cls}(Interface):
    """Base interface for {name} implementations."""

    registry = {registry_cls}

    def run(self):
        """Override in concrete implementations."""
        raise NotImplementedError
'''


def render_implementations_module(name: str) -> str:
    """Return the source for an implementations module with one sample impl."""
    interface_cls = f"{name}Interface"
    return f'''"""Concrete {name} implementations.

Each class auto-registers because it inherits `registry` from the interface
and sets a unique `slug`.
"""

from .registry import {interface_cls}


class Default{name}({interface_cls}):
    slug = "default"
    description = "Default {name} implementation"

    def run(self):
        return "default"
'''


def write_registry_files(
    base_dir: str | Path,
    name: str,
    module: str,
    *,
    force: bool = False,
) -> list[Path]:
    """Write ``registry.py`` and ``<module>.py`` into ``base_dir``.

    Raises ``CommandError`` if a target file already exists and ``force`` is
    False. Returns the list of written paths.
    """
    base = Path(base_dir)
    targets = [
        (base / "registry.py", render_registry_module(name, module)),
        (base / f"{module}.py", render_implementations_module(name)),
    ]

    for path, _ in targets:
        if path.exists() and not force:
            raise CommandError(f"{path} already exists; pass --force to overwrite")

    written: list[Path] = []
    for path, content in targets:
        path.write_text(content)
        written.append(path)
    return written
