"""`startregistry` management command: scaffold a new registry into an app."""

from __future__ import annotations

import keyword
import re
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError


def _validate_identifier(value: str, label: str) -> None:
    """Raise CommandError unless ``value`` is a safe, plain ASCII Python identifier.

    Guards against generating syntactically broken source (the value is
    interpolated into class names and a module name), path traversal (the module
    name is used as a filename), surprising non-ASCII identifiers, and dunder
    names that could clobber package files such as ``__init__``.
    """
    if not value.isidentifier() or keyword.iskeyword(value):
        raise CommandError(f"{label} must be a valid Python identifier, got {value!r}")
    if not value.isascii():
        raise CommandError(f"{label} must be ASCII, got {value!r}")
    if value.startswith("__") and value.endswith("__"):
        raise CommandError(f"{label} must not be a dunder name, got {value!r}")


def to_snake(name: str) -> str:
    """Convert a CamelCase or PascalCase name to snake_case."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def render_registry_module(name: str, module: str) -> str:
    """Return the source for a registry module defining a Registry + Interface."""
    registry_cls = f"{name}Registry"
    interface_cls = f"{name}Interface"
    return f'''"""Registry definition generated by `manage.py startregistry`."""

from django_stratagem.interfaces import Interface
from django_stratagem.registry import Registry


class {registry_cls}(Registry):
    """Registry of {name} implementations."""

    implementations_module = "{module}"


class {interface_cls}(Interface):
    """Base interface for {name} implementations."""

    registry = {registry_cls}

    def run(self):
        """Override in concrete implementations."""
        raise NotImplementedError
'''


def render_implementations_module(name: str) -> str:
    """Return the source for an implementations module with one sample impl."""
    interface_cls = f"{name}Interface"
    return f'''"""Concrete {name} implementations.

Each class auto-registers because it inherits `registry` from the interface
and sets a unique `slug`.
"""

from .registry import {interface_cls}


class Default{name}({interface_cls}):
    slug = "default"
    description = "Default {name} implementation"

    def run(self):
        return "default"
'''


def write_registry_files(
    base_dir: str | Path,
    name: str,
    module: str,
    *,
    force: bool = False,
) -> list[Path]:
    """Write ``registry.py`` and ``<module>.py`` into ``base_dir``.

    Raises ``CommandError`` if a target file already exists and ``force`` is
    False. Returns the list of written paths.
    """
    base = Path(base_dir)
    targets = [
        (base / "registry.py", render_registry_module(name, module)),
        (base / f"{module}.py", render_implementations_module(name)),
    ]

    # Back up the original content of any file we are about to overwrite so a
    # mid-write failure can be rolled back to the exact prior state.
    backups = {path: path.read_text() for path, _ in targets if path.exists()}
    if backups and not force:
        existing = ", ".join(sorted(str(p) for p in backups))
        raise CommandError(f"Already exists (pass --force to overwrite): {existing}")

    written: list[Path] = []
    try:
        for path, content in targets:
            path.write_text(content)
            written.append(path)
    except OSError as exc:
        # Restore overwritten files to their original content and remove files
        # this command newly created, so a failed write leaves no partial state.
        for path in written:
            if path in backups:
                path.write_text(backups[path])
            else:
                path.unlink(missing_ok=True)
        raise CommandError(f"Failed to write registry files: {exc}") from exc
    return written


class Command(BaseCommand):
    help = "Scaffold a new django-stratagem registry into an app."

    def add_arguments(self, parser):
        parser.add_argument("name", help="Registry base name, e.g. 'Notification'")
        parser.add_argument("--app", required=True, help="Target app label")
        parser.add_argument(
            "--module",
            default=None,
            help="Implementations module name (default: <name>_implementations)",
        )
        parser.add_argument(
            "--force",
            action="store_true",
            help="Overwrite existing files",
        )

    def handle(self, *args, **options):
        from django.apps import apps

        name = options["name"]
        app_label = options["app"]
        _validate_identifier(name, "name")
        module = options["module"] or f"{to_snake(name)}_implementations"
        _validate_identifier(module, "--module")
        if module.casefold() == "registry":
            raise CommandError("--module 'registry' collides with the generated registry.py; choose another name")

        try:
            app_config = apps.get_app_config(app_label)
        except LookupError as exc:
            raise CommandError(f"No installed app with label '{app_label}'") from exc

        written = write_registry_files(app_config.path, name, module, force=options["force"])
        for path in written:
            self.stdout.write(self.style.SUCCESS(f"Created {path}"))  # type: ignore[attr-defined]

        self.stdout.write(
            "Next steps: make sure the app is in INSTALLED_APPS. "
            "The registry auto-discovers its implementations on startup."
        )
