# Generated by Django 6.0.2 on 2026-02-14 06:05

from django.db import migrations, models

import django_stratagem.fields
import tests.registries_fixtures


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistryFieldTestModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Test", max_length=100)),
                (
                    "single_instance",
                    django_stratagem.fields.RegistryField(
                        blank=True,
                        help_text="Single implementation instance field",
                        null=True,
                        registry=tests.registries_fixtures.TestStrategyRegistry,
                    ),
                ),
                (
                    "single_class",
                    django_stratagem.fields.RegistryClassField(
                        blank=True,
                        help_text="Single implementation class field",
                        null=True,
                        registry=tests.registries_fixtures.TestStrategyRegistry,
                    ),
                ),
                (
                    "multiple_instances",
                    django_stratagem.fields.MultipleRegistryField(
                        blank=True,
                        help_text="Multiple implementation instances field",
                        registry=tests.registries_fixtures.TestStrategyRegistry,
                    ),
                ),
                (
                    "multiple_classes",
                    django_stratagem.fields.MultipleRegistryClassField(
                        blank=True,
                        help_text="Multiple implementation classes field",
                        registry=tests.registries_fixtures.TestStrategyRegistry,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registry Field Test Model",
                "verbose_name_plural": "Registry Field Test Models",
            },
        ),
    ]
