# Generated by Django 6.0.2 on 2026-05-24 00:08

from django.db import migrations, models

import django_stratagem.fields
import examples.payments.registry


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "gateway",
                    django_stratagem.fields.RegistryClassField(
                        blank=True,
                        help_text="The payment gateway this merchant uses",
                        null=True,
                        registry=examples.payments.registry.PaymentGatewayRegistry,
                    ),
                ),
            ],
        ),
    ]
